### ISSUE TITLE
Release build (UWP ARM64) with Serilog.Expressions fails to compile

### ISSUE THREAD

**Issue by trandzik** [serilog/serilog-expressions#122]
**Description**
I am having a hard time compiling Release build of UWP application (ARM64) when Serilog.Expressions package is installed. Debug build seems to work fine, however Release fails with following error:
~~~
C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\Microsoft.NetNative.targets(809,5): error : ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-arm64.microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\ARM64\ilc\Tools64\nutc_driver.exe @"C:\proj\TestAppBuild\obj\ARM64\Release\ilc\intermediate\MDIL\TestAppBuild.rsp"' returned exit code -1073741819
~~~
Please do you have some idea what could be causing this? Thanks.

**Reproduction**
Open latest version of Visual Studio 2022 and create a new project. Select C# template "Blank App (Universal Windows)". Add Serilog.Expressions NuGet package to the project. Select Release configuration for ARM64 and build the solution.

**Expected behavior**
Successful compilation.

**Relevant package, tooling and runtime versions**
Latest Serilog.Expressions package (5.0.0) on UWP ARM64.
Used UWP template also contains Microsoft.NETCore.UniversalWindowsPlatform package (6.2.14).

**Additional context**
None

**Comment by nblumhardt** [comment]
Hi Peter, thanks for your message. No ideas, unfortunately.

This seems to be a .NET Native toolchain error, rather than a Serilog.Expressions issue, so you're more likely to find people experienced in this via Stack Overflow (feel free to also post a link here).

From what I could see in other similar threads, there may be a line before the error above that mentions which method failed to compile - this would also be good to include in the Stack Overflow post if you're able to track that info down.

Hope this helps,
Nick

**Comment by trandzik** [comment]
Hi Nick, thanks for reply and info.

I have just posted the [question on Stack Overflow,](https://stackoverflow.com/questions/78808233/uwp-release-build-arm64-fails-to-compile), hopefully someone there will know what it means. Unfortunately there doesn't seem to be any helpful line before the error.
