### ISSUE TITLE
[Question] Not compatible with .NET Framework 4.7.x?

### ISSUE THREAD

**Issue by lennartb-** [serilog/serilog-expressions#13]
Hi,

I'm not sure if it's intentional, but the package is currently only installable for .NETStandard,Version=v2.1. All other Serilog packages (that we use, and also Serilog.Filters.Expressions which is the reason I install this) are also compatible with the regular .NET Framework.

Is this something you can add, or do we need to stick to Serilog.Filters.Expressions?

Regards,
Lennart

**Comment by nblumhardt** [comment]
Hi Lennart,

Thanks for your message. It's somewhat intentional - supporting .NET Framework is starting to impose a burden I think we should avoid in new Serilog sub-projects - C# features and now-fundamental types are unavailable on .NET Framework.

Sticking to _Serilog.Filters.Expressions_ is the way to go for now, but there's definitely room for more thought/discussion around what our strategy should be, here.

**Comment by lennartb-** [comment]
Thanks for the clarification, then we'll have to stick to Serilog.Filters.Expressions for the time being. Maybe this pushes us a bit towards a migration to Standard :)

I'm not sure what could be an alternative strategy here, if the package only relies on newer features only sparingly, one could probably get away with different targets and `#if NETFRAMEWORK`s but ehh, I'd understand not going with this.

**Comment by chucklu** [comment]
Same problem, can not install this library to project with .net 4.7.2 framework.

**Comment by VictorioBerra** [comment]
Please do not archive or take down Serilog.Filters.Expressions from NuGet.

**Comment by nblumhardt** [comment]
Hi @VictorioBerra ! --- Not to worry at all, _Serilog.Filters.Expressions_ will be up there for as long as nuget.org will host it 👍 

The aim isn't to make using Serilog on .NET Framework harder - just to make sure we can keep improving and maintaining Serilog effectively into the future.

Since .NET Framework is now effectively "frozen in time", I think the strategy that makes the most sense is to keep supporting it via the frozen set of packages and versions that already target it. What do you think?

**Comment by VictorioBerra** [comment]
@nblumhardt I am not against that, as long as "support" means bug and security fixes? I can understand features and enhancements going to netstandard/net5.0+ going forward.

**Comment by nblumhardt** [comment]
@VictorioBerra thanks for the reply! Bugs and security fixes will always come down to people being there to submit and review PRs, which becomes less certain as a package ages out of circulation, but for the foreseeable future there should be a vehicle to get these out for Serilog.Filters.Expressions, as we do for Serilog.Sinks.RollingFile, which was deprecated quite a while ago.

In my experience so far, there's a wide spectrum of support even within the Serilog project. Some libraries, where the users maintain them and the maintainers use them, keep up good momentum (Serilog.Sinks.File and Console are good examples). In others, the maintainers don't use them, and the users don't maintain them (which requires long-term involvement rather than just an occasional PR), the PRs tend to build up unanswered and things don't move forward much (Serilog.Sinks.Email is one that comes to mind right now).

I'm not sure if this is just the natural way of things, or if there's more we could do to improve (encouraging new maintainers to join and helping them become productive is an obvious avenue we could explore...)

I'd say Serilog.Filters.Expressions is closer to the former than the latter - I still use it in various places, and I know quite a few others do, so it's likely to get some attention 👍
