### ISSUE TITLE
[Question] Timestamp format on json template

### ISSUE THREAD

**Issue by josemnbcamacho** [serilog/serilog-expressions#18]
Hi,

I'm trying to use a timestamp formatter in a json template like

`"{ {timestamp: @t:o, level: @l, sourceContext: SourceContext, message: @m} }\n"`

Can't manage to get the formatted timestamp, it seems that the parser is not expecting the ":" after "@t".

Is this something supported?

Regards,
José

**Comment by nblumhardt** [comment]
Hi Jose - unfortunately, this syntax isn't supported; `o` should be the default format for datetimes, IIRC, so you may not need it at all (?), but otherwise, plugging in a `ToString()` [user-defined function](https://github.com/serilog/serilog-expressions#implementing-user-defined-functions) would be the only way to work around this right now:

```
"{ {timestamp: ToString(@t, 'o'), level: @l, sourceContext: SourceContext, message: @m} }\n"
```

We might add a `ToString(x, format)` built-in function to handle these kinds of cases.
