### ISSUE TITLE
Add a .NET Standard 2.0 target

### ISSUE THREAD

**Issue by f2calv** [serilog/serilog-expressions#24]
First a great library thanks :)
However it appears to be a unique Serilog library in that its the only one that isn't backward compatible with .NET Standard 2.0;

![image](https://user-images.githubusercontent.com/16097639/109751010-da932f80-7bdd-11eb-8e0f-990bbc136c0e.png)

**Comment by nblumhardt** [comment]
Wowsers, that's quite a few Serilog package dependencies you have there! 😅 

I'm open to adding `netstandard2.0` support if we can do it without degrading the quality of the codebase; it's been a while since I looked into it, so might need some experimentation - would be great to know how much needs to change, if you have the time to try it out!

Otherwise, I'll loop back around and take a look as soon as I can. Cheers!

**Comment by f2calv** [comment]
Already done ;)
